version: "3.8"

services:
  ray_mongo1:
    image: mongo:4.4.6
    container_name: ray_mongo1
    hostname: ray_mongo1
    command:
      [
        "mongod",
        "--replSet",
        "rs1",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    volumes:
      - ray_mongo1:/data/db
    ports:
      - 27017:27017
    networks:
      - ray
  mongo_init_replica:
    image: mongo:4.4.6
    container_name: mongo_init_replica
    volumes:
      - "./.docker/mongo_init.sh:/scripts/mongo_init.sh:ro"
    entrypoint: [ "bash", "/scripts/mongo_init.sh"]
    depends_on:
      - ray_mongo1
    networks:
      - ray

volumes:
  ray_mongo1:


networks:
  ray:
